project_id = "lyfos-vault-local"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 17
health_timeout = "2m"

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[realtime]
enabled = true

[studio]
enabled = true
port = 55323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 55324

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8183

[analytics]
enabled = false
port = 55327
backend = "postgres"

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173/**", "https://app.lyfos.in/**"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 8

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[functions.send-key-holder-invite]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-recovery-notifications]
verify_jwt = true
